### ISSUE TITLE
Complete how you can contribute section

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/paleo#1]
The "how you can contribute" section of the [README](https://github.com/tdwg/paleo/blob/master/README.md) currently only has boilerplate text:

> Depending on where group interaction takes place (GitHub, mailing list), provide some guidance on how interested parties can follow group activities (e.g. watch this repository, join mailing list) and how they can contribute.

**Comment by dennereed** [comment]
Updated How You Can Contribute section of README
