### ISSUE TITLE
Should there be an agreed best practice for ISO time used for dcterms:modified

### ISSUE THREAD

**Issue by dennereed** [tdwg/paleo#5]
Darwin Core recommends, but does not require, a standard format for date-time representations and it suggests ISO 8601. The standard is reasonably well documented on wikipedia, but the full documentation for the standard requires purchase from ISO. The questions then to Paleo IG are: 1) should we specify ISO 8601 as best practice? 2) If not, is there a free and open alternative?

**Comment by DimEvil** [comment]
We do not use date modified anymore, this is the TDWG guideline: http://rs.tdwg.org/dwc/terms/#dcterms:modified 
1) don't bother for this field
2) YYYY-MM-DD would be fair. But if you need the exact time pon the second, you can use this:

Date and time 
expressed according to ISO 8601:
Date:	2017-03-09
Combined date and time in UTC:	2017-03-09T10:44:47+00:00


further, if you wan't to publish (also) to GBIF. GBIF can't interpret dateRanges (intervals), even if they are aloud in the DWC. (This is also the case for eventDate)

**Comment by dennereed** [comment]
Created wiki page to document and clarify use of this term in Darwin Core paleo, recommending DwC-paleo best practice is to follow DwC docs, but emphasizing that dcterms:modified refers to date and time that the digital resource was modified and not when the basis for the occurrence (i.e. the fossil) was modified.  Clarification is relevant to paleo because our occurrences reference physical objects and this is a possible point of confusion.
